/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Controlador.ProveedorDO;
import Modelo.Conexion;
import Modelo.ProveedorDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel
 */
public class ConsultaProveedores extends javax.swing.JFrame {

    
    public ProveedorDO pdo = new ProveedorDO();
    
    public ConsultaProveedores() {
        initComponents();
    }
    
    
    
    ////////*Conexion con DO*//////////////
    public void listarProveedores() throws SQLException{
       pdo.listarProveedor(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtBusquedaRutProveedores = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConsultaProve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnListarProveedores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel2.setText("Busqueda RUT Proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtBusquedaRutProveedores.setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().add(txtBusquedaRutProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 120, -1));

        jTable1.setBackground(new java.awt.Color(255, 204, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 650, 110));

        btnConsultaProve.setText("Consulta");
        btnConsultaProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaProveActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 153, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logochico.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 200, 90));

        btnListarProveedores.setText("Listar Proveedores");
        btnListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 153, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/orange-gradient-wallpaper-4422.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 360));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProveedoresActionPerformed
        try {
            listarProveedores();
            //txtTotalProve.setText(jTable1.getRowCount()+"");
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarProveedoresActionPerformed

    private void btnConsultaProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaProveActionPerformed

    }//GEN-LAST:event_btnConsultaProveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Volver Al menu Principal?, "
                + "Recuerda Guardar tus Cambios", 
                 " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
            try {
                InicioMenuPrincipalAdmin inicio = new InicioMenuPrincipalAdmin();
                inicio.setVisible(true);
                dispose();
                //System.exit(0);
            } catch (SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(RegistrarProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Salir del Sistema?, "
                + "Recuerda Guardar tus Cambios", 
                  " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
              getToolkit().beep();
              System.exit(0);
              System.out.println("Sistema Cerrado Correctamente");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaProve;
    private javax.swing.JButton btnListarProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusquedaRutProveedores;
    // End of variables declaration//GEN-END:variables
}
