/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Pedido_ProvedorDO;
import Controlador.ProductosDO;
import Controlador.ProveedorDO;
import Modelo.CategoriaDAO;
import Modelo.Categorias;
import Modelo.Conexion;
import Modelo.Pedido_Provedor;
import Modelo.Pedido_ProvedorDAO;
import Modelo.Productos;
import Modelo.ProductosDAO;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel
 */
public class GestionProductosAdmin extends javax.swing.JFrame {

    //Instacia a DAO
    ProductosDAO proddao = new ProductosDAO();
    CategoriaDAO catdao = new CategoriaDAO();
    Pedido_ProvedorDAO ppdao = new Pedido_ProvedorDAO();
    
    DefaultTableModel model;
    
    //Instancia a DO
    private ProveedorDO pdo = new ProveedorDO();
    private ProductosDO prodo = new ProductosDO();
    private Pedido_ProvedorDO ppdo = new Pedido_ProvedorDO();
    /**
     * Creates new form GestionProductos
     * @throws java.sql.SQLException
     */
    public GestionProductosAdmin() throws SQLException {
        initComponents();
        setSize(801, 680);
        setResizable(false);
        setTitle("Acceso Gestion Productos");
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/Img/orange-gradient-wallpaper-4422.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel17.getWidth(), 
        jLabel17.getHeight(), Image.SCALE_DEFAULT));
        jLabel17.setIcon(icono);
        this.repaint();
       
        
        ///Lenado Combobox desde BD
        this.cbCategoria.removeAllItems();
        try {
            Connection con = Conexion.getConnection();
            //PreparedStatement pst = null;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM CATEGORIAS");
            while (rs.next()) {
                this.cbCategoria.addItem(rs.getString("CATEGORIA"));
            }
        } catch (Exception e) {
            System.err.println("Error de llenado ComboBox Desde BD " +  e);
        }
        
        
        //***///////////////////////////////////////////
        ListarProvAct(); //Inizializa la lista de activos (provedores)
        listarProve(); //Inicializa la lista de provedores
        listarProd();
        idMax(); //Inicializa el proximo ID en el campo de texto
        
        //Fecha
        Calendar calendar = new GregorianCalendar();
        txtFecha.setText(""+calendar.get(Calendar.YEAR)+"-"+calendar.get(Calendar.MONTH)+"-"+calendar.get(Calendar.DAY_OF_MONTH));
        //txtID_Cate.setText(cbCategoria.getItemAt(cbCategoria.getSelectedIndex())+"");
    }
    
    public void listarProve() throws SQLException{
      //pdo.listarProveedor(jTable3);
    }
    
    public void listarProd() throws SQLException{
      //pdo.listarProveedor(jTable2);
      prodo.listarProductos(jTable2);
    }
    
    public void ListarProvAct() throws SQLException{
      pdo.ListarProvAct(jTable3);
    }
    
    public void idMax(){
      txtIdProducto.setText(prodo.getMaxIDProductos()+"");
    }
    
    public void Limpiar(){
        //productos
        txtIdProducto.setText("");
        txtNombreProd.setText("");
        txtPrecioPro.setText("");
        txtDescriPro.setText("");
        txtID_Cate.setText("");
        txtCantPro.setText("");
        txtFecha.setText("");
        
        //Provedores
        txtCodProveReg.setText("");
        txtEstadoProv.setText("");
        //txtIDproveProd.setText("");
        txtRutProvProd.setText("");
        txtNomProPro.setText("");
        txtTelProvProd.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbCategoria = new javax.swing.JComboBox<>();
        txtIdProducto = new javax.swing.JTextField();
        txtNombreProd = new javax.swing.JTextField();
        txtPrecioPro = new javax.swing.JTextField();
        txtCantPro = new javax.swing.JTextField();
        txtDescriPro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodProveReg = new javax.swing.JTextField();
        btnBuscarProve = new javax.swing.JButton();
        txtRutProvProd = new javax.swing.JTextField();
        txtNomProPro = new javax.swing.JTextField();
        txtTelProvProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAgregarPro = new javax.swing.JButton();
        btnFacturaVenta = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        btnSolicitar = new javax.swing.JButton();
        txtID_Cate = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        txtEstadoProv = new javax.swing.JTextField();
        btnLimpiarProd = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtStock_Minimo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbCategoria.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        cbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoriaItemStateChanged(evt);
            }
        });
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 173, -1));

        txtIdProducto.setEditable(false);
        getContentPane().add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 74, -1));

        txtNombreProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProdKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 74, -1));

        txtPrecioPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecioPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 74, -1));

        txtCantPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantProKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, -1));

        txtDescriPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescriProKeyTyped(evt);
            }
        });
        getContentPane().add(txtDescriPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 74, -1));

        jTable2.setBackground(new java.awt.Color(255, 102, 0));
        jTable2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 720, 100));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel1.setText("ID/Prod");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("Catego");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("Descripc");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("COD/PROVE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 41, -1, -1));
        getContentPane().add(txtCodProveReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 38, 54, -1));

        btnBuscarProve.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnBuscarProve.setText("Agregar Provedor");
        btnBuscarProve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnBuscarProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 39, 100, 20));
        getContentPane().add(txtRutProvProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 94, 102, -1));
        getContentPane().add(txtNomProPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 94, 90, -1));
        getContentPane().add(txtTelProvProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 94, 110, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel8.setText("Rut Prv");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 74, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 74, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel10.setText("Telefono");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 74, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logochico.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 233, -1));

        jTable3.setBackground(new java.awt.Color(255, 102, 0));
        jTable3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 132, 439, 91));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel13.setText("Fecha Pedido");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 170, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel14.setText("Total");

        btnAgregarPro.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnAgregarPro.setText("Agregar");
        btnAgregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProActionPerformed(evt);
            }
        });

        btnFacturaVenta.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnFacturaVenta.setText("Fact");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel15.setText("IVA");

        btnSolicitar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnSolicitar.setText("Solicitar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAgregarPro)
                .addGap(18, 18, 18)
                .addComponent(btnFacturaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSolicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPro)
                    .addComponent(btnFacturaVenta)
                    .addComponent(jLabel15)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSolicitar))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 720, -1));

        txtID_Cate.setEditable(false);
        getContentPane().add(txtID_Cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 26, -1));
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 861, -1, -1));
        getContentPane().add(txtEstadoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 70, -1));

        btnLimpiarProd.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnLimpiarProd.setText("Limpiar");
        btnLimpiarProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 80, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel18.setText("Stock Minimo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        txtStock_Minimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStock_MinimoKeyTyped(evt);
            }
        });
        getContentPane().add(txtStock_Minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 60, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/orange-gradient-wallpaper-4422.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 800, 900));

        jLabel16.setText("ID/CAT");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cerrar Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
    
        String estado = "ACTIVO";//txtEstadoProv.getText();
      
        int seleccion = jTable3.rowAtPoint(evt.getPoint());
          txtCodProveReg.setText(jTable3.getValueAt(seleccion, 0)+"");
          txtRutProvProd.setText(jTable3.getValueAt(seleccion, 1)+"");
          txtNomProPro.setText(jTable3.getValueAt(seleccion, 2)+"");
          txtTelProvProd.setText(jTable3.getValueAt(seleccion, 6)+"");
        if(estado.equals(estado)){
            txtEstadoProv.setText(jTable3.getValueAt(seleccion, 8)+"");
            txtEstadoProv.setBackground(Color.green);
        }  
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnAgregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProActionPerformed
       
        if (txtIdProducto.getText().isEmpty()
            || txtNombreProd.getText().isEmpty()
            || txtPrecioPro.getText().isEmpty()
            || txtDescriPro.getText().isEmpty() 
            || txtCantPro.getText().isEmpty() 
            || txtStock_Minimo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Hay Campos Vacios, Debes llenar los Campos Solicitados");
        }else{
            Categorias cate = new Categorias();
            Productos prod = new Productos();
            Pedido_Provedor pp = new Pedido_Provedor();
            
            prod.setID_PRODUCTO(Integer.parseInt(txtIdProducto.getText()));
            prod.setNOMBRE(txtNombreProd.getText());
            prod.setPRECIO_UNITARIO(Integer.parseInt(txtPrecioPro.getText()));
            prod.setDESCRIPCION(txtDescriPro.getText());
            prod.setID_CATEGORIA(Integer.parseInt(txtID_Cate.getText()));
            prod.setCANTIDAD(Integer.parseInt(txtCantPro.getText()));
            prod.setSTOCK_MINIMO(Integer.parseInt(txtStock_Minimo.getText()));
            JOptionPane.showMessageDialog(null, "Grabado Existoso del Producto");
            String mensaje = prodo.agregarProductos(prod);
            try {
                listarProd();
            } catch (SQLException e) {
               JOptionPane.showMessageDialog(null," Error de guardado de Producto" + e);
            }
        }
    }//GEN-LAST:event_btnAgregarProActionPerformed

    private void cbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoriaItemStateChanged
        //cate.setID_CATEGORIA();
        //txtID_Cate.setText(cbCategoria.getItemAt(cbCategoria.getSelectedIndex())+"");
        //Categorias cate = (Categorias)cbCategoria.getSelectedItem();
        //cate.setID_CATEGORIA(Integer.parseInt(txtID_Cate.getText()));
    }//GEN-LAST:event_cbCategoriaItemStateChanged

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        try {
            Connection con = Conexion.getConnection();
            //PreparedStatement pst = null;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM CATEGORIAS WHERE CATEGORIA ='"+ this.cbCategoria.getSelectedItem()+"'");
            //tring sql = ("SELECT * FROM CATEGORIAS WHERE CATEGORIA ='"+ this.cbCategoria.getSelectedItem()+"'");
            rs.next();
            this.txtID_Cate.setText(String.valueOf(rs.getInt("ID_CATEGORIA")));
            txtID_Cate.setBackground(Color.GREEN);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void btnLimpiarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarProdActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarProdActionPerformed

    
 //Eventos de Restriccion de caracteres

    private void txtNombreProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProdKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            txtNombreProd.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo Letras");
        }
    }//GEN-LAST:event_txtNombreProdKeyTyped

    private void txtDescriProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriProKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            txtDescriPro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo Letras");
        }
    }//GEN-LAST:event_txtDescriProKeyTyped

    private void txtPrecioProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            txtPrecioPro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtPrecioProKeyTyped

    private void txtCantProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantProKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            txtCantPro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtCantProKeyTyped

    private void txtStock_MinimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStock_MinimoKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            txtCantPro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtStock_MinimoKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Vovel al menu de Administrador?, "
                + "Recuerda Guardar tus Cambios", 
                 " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){                       
            try {
                InicioMenuPrincipalAdmin a = new InicioMenuPrincipalAdmin();
                a.setVisible(true);
                dispose();
            } catch (SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(GestionProductosAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Salir del Sistema?, "
                + "Recuerda Guardar tus Cambios", 
                 " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
                System.exit(0);
                getToolkit().beep();
                System.out.println("Cerrado exitoso");
            } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPro;
    private javax.swing.JButton btnBuscarProve;
    private javax.swing.JButton btnFacturaVenta;
    private javax.swing.JButton btnLimpiarProd;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<Object> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCantPro;
    private javax.swing.JTextField txtCodProveReg;
    private javax.swing.JTextField txtDescriPro;
    private javax.swing.JTextField txtEstadoProv;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID_Cate;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNomProPro;
    private javax.swing.JTextField txtNombreProd;
    private javax.swing.JTextField txtPrecioPro;
    private javax.swing.JTextField txtRutProvProd;
    private javax.swing.JTextField txtStock_Minimo;
    private javax.swing.JTextField txtTelProvProd;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
