/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Conexion;
import static Vistas.InicioMenuPrincipalAdmin.sesion_usuario;
import static Vistas.Login.TWO_SECOND;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.WindowConstants;

/**
 *
 * @author samuel
 */
public class IncioBodeguero extends javax.swing.JFrame {
    private Timer timer;
    int cont;
    public final static int TWO_SECOND=5;
    //******
    String user, nombre_usuario, hola ;
    public static int sesion_usuario;
    /**
     * Creates new form IncioBodeguero
     */
    public IncioBodeguero() {
        initComponents();
        barra.setVisible(false);
        this.setLocationRelativeTo(null);
        setSize(597, 382);
        setResizable(false);
        setLocationRelativeTo(null);
        
        ImageIcon wallpaper = new ImageIcon("src/Img/orange-gradient-wallpaper-4422.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1.getWidth(), 
        jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        this.repaint();
        user =Login.user;
        sesion_usuario = 1;
        setTitle("Bodega- sesion actual : "+ user);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ////////
        ///***Hilo para movimiento de texto InicioAdmin
        new Thread(){
            public void run(){
                int x = 300;
                int y = jLabel2.getLocation().y;
                
                while(true){
                    x--;
                    if(x < -100){
                        x = getWidth();
                    }
                    jLabel2.setLocation(x, y);
                    try{
                        sleep(10);
                    }catch(Exception e){ 
                    }
                }
            }
        }.start();
        
        //////////////
        //Fecha ////
          Date fecha = new Date(); //fecha y hora actual
          SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); //formatear la fecha en una cadena
          String hora = sdf.format(fecha); //setear la representacion en cadena de la fecha
        
        /////////////
        try {
            Connection con = Conexion.getConnection();
            PreparedStatement pst = con.prepareStatement(
            "SELECT USUARIO FROM EMPLEADOS WHERE USUARIO = '" + user + "'");

            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("USUARIO");
                jLabel2.setText("Bienvenido : " + nombre_usuario.toUpperCase() + " - "+  " La fecha Actual es  : " + hora);
            }
        } catch (Exception e) {
            System.err.println(" Error de Conexion Desde la Interfaz Admin"+ e);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        barra.setForeground(new java.awt.Color(51, 51, 51));
        barra.setStringPainted(true);
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logochico.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 600, 350));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Buscar.png"))); // NOI18N
        jMenu3.setText("Menu");

        jMenuItem2.setText("Salir");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        jMenu2.setText("Solicitar Productos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class TimerListener implements ActionListener{
        
        public void actionPerformed(ActionEvent e) {
            cont++;
            barra.setValue(cont);
            if(cont==100){
                timer.stop();
                 SolicitarProductosBodega s = null;
            try {
                s = new SolicitarProductosBodega();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(IncioBodeguero.class.getName()).log(Level.SEVERE, null, ex);
            }
                s.setVisible(true);
            }
        }
    }
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

        barra.setVisible(true);
        cont=-1;
        barra.setValue(0);
        barra.setStringPainted(true);
        timer=new Timer(TWO_SECOND, new TimerListener());
        timer.start();
        if(barra.getValue()==100){
            this.dispose();
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Salir del Sistema?, "
                + "Recuerda Guardar tus Cambios", 
                  " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){ 
                Login l = new Login();
                l.setVisible(true);
                dispose();
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
