/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import Modelo.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author samuel
 */
public class Login extends javax.swing.JFrame {
    //**Variables de Barra Progreso
    private Timer timer;
    int cont;
    public final static int TWO_SECOND=3;
    //******
    public static String user = "";
    String pass = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(400,550);
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);
        barra.setVisible(false);
        
        ImageIcon wallpaper = new ImageIcon("src/Img/orange-gradient-wallpaper-4422.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1_wall.getWidth(), 
                jLabel1_wall.getHeight(), Image.SCALE_DEFAULT));
        jLabel1_wall.setIcon(icono);
        this.repaint();
        
        ///***Hilo para movimiento de texto InicioAdmin
        new Thread(){
            @Override
            public void run(){
                int x = 300;
                int y = txtMovimiento.getLocation().y;
                
                while(true){
                    x--;
                    if(x < -100){
                        x = getWidth();
                    }
                    txtMovimiento.setLocation(x, y);
                    try{
                        sleep(10);
                    }catch(Exception e){ 
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUserLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMovimiento = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassLogin = new javax.swing.JPasswordField();
        barra = new javax.swing.JProgressBar();
        jLabel1_wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logochico.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 260, -1));

        txtUserLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel3.setText("Ingrese Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel4.setText("Ingrese Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        txtMovimiento.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtMovimiento.setText("Version 1.5 | Derechos Reservados | siglo21.portafolio@gmail.com");
        getContentPane().add(txtMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        txtPassLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 120, -1));

        barra.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        barra.setForeground(new java.awt.Color(51, 51, 51));
        barra.setStringPainted(true);
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, 20));
        getContentPane().add(jLabel1_wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //**Clase Timer para Barra Progeso
    public class TimerListener implements ActionListener{
        public void actionPerformed(ActionEvent e) {
            cont++;
            barra.setValue(cont);
            if(cont==100){
                timer.stop();
                //InicioAdmin ia= new InicioAdmin();
                //ia.setVisible(true);
                 new InicioAdmin().setVisible(true);
                 dispose();
            }
        }
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //'" + user + "'
        //'" + pass + "'"
        user = txtUserLogin.getText().trim().toLowerCase();
        pass = txtPassLogin.getText().trim().toLowerCase();
        if(!user.equals("") || !pass.equals("")){
             try{
                 Connection con = Conexion.getConnection();
                 PreparedStatement pst = con.prepareStatement(
                 "SELECT ID_CARGO, STATUS_EMPLEADO FROM EMPLEADOS WHERE USUARIO = ?  AND PASS = ?");
                 pst.setString(1, user);
                 pst.setString(2, pass);
                 ResultSet rs = pst.executeQuery();
                 if(rs.next()){
                        
                     //pst.setString(1, user);
                     //pst.setString(2, pass);
                     int ID_CARGO = rs.getInt("ID_CARGO");
                     String STATUS_EMPLEADO = rs.getString("STATUS_EMPLEADO");
                     
                     if(ID_CARGO== 1  && STATUS_EMPLEADO.equalsIgnoreCase("ACTIVO")){
                        barra.setVisible(true);
                        cont=-1;
                        barra.setValue(0);
                        barra.setStringPainted(true);
                        timer=new Timer(TWO_SECOND, new TimerListener());
                        timer.start();
                        if(barra.getValue()==100){
                            this.dispose();
                        }
                        //dispose();
                        //new InicioAdmin().setVisible(true);
                        
                        }else if(ID_CARGO== 6  && STATUS_EMPLEADO.equalsIgnoreCase("ACTIVO")){
                          dispose();
                          new IncioBodeguero().setVisible(true);
                        }else if(ID_CARGO== 2  && STATUS_EMPLEADO.equalsIgnoreCase("ACTIVO")){
                           
                          dispose();
                          new InicioFinanzas().setVisible(true);
                        }
                 }else{
                     JOptionPane.showMessageDialog(null, "Datos de Acceso Incorrectos");
                     System.err.println("Datos de Acceso Incorrectos");
                     txtUserLogin.setText("");
                     txtPassLogin.setText("");
                     con.close();
                }
                 
             }catch(SQLException | HeadlessException e){
                 System.err.println("Error "+ e);
                 JOptionPane.showMessageDialog(null, "Error al conectarse, consulte al administrador");
             }
             
        }else{
            JOptionPane.showMessageDialog(null, "Disculpa,debes llenar Los campos Vacios");  
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1_wall;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtMovimiento;
    private javax.swing.JPasswordField txtPassLogin;
    private javax.swing.JTextField txtUserLogin;
    // End of variables declaration//GEN-END:variables
}
