/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.ProveedorDO;
import Modelo.Proveedor;
import Modelo.ValidadorEmail;
import Modelo.ValidadorRut;
import static Vistas.SolicitudesProduAdmin.sesion_usuario;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel
 */
public final class RegistrarProveedores extends javax.swing.JFrame {
    String user, nombre_usuario, hola ;
    DefaultTableModel model;
    /**
     * Creates new form RegistrarProveedores
     */
    private final ProveedorDO pdo = new ProveedorDO();
    public ValidadorEmail IsEmail = new ValidadorEmail();
    public ValidadorRut validaRut = new ValidadorRut();
    
    public RegistrarProveedores() throws SQLException {
        initComponents();
        setSize(929, 482);
        setResizable(false);
        setTitle("Solicitud Insumos");
        setLocationRelativeTo(null);
        //*Wallpaper 
        ImageIcon wallpaper = new ImageIcon("src/Img/orange-gradient-wallpaper-4422.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel1.getWidth(), 
        jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        this.repaint();
        
        user =Login.user;
        sesion_usuario = 1;
        setTitle("Administrador- sesion actual : "+ user);
        listarProve();
        idMax();
        
    }
    
    public void listarProve() throws SQLException{
      pdo.listarProveedor(jTable1);
    }
    
    public void idMax(){
      txtIDProve.setText(pdo.getMaxID()+"");
    }
    
    void bloquear(){
        txtRutRegistro.setEnabled(true);
        txtNombreContactoRegistro.setEnabled(true);
        txtWebRegistro.setEnabled(true);
        txtNombreRegistro.setEnabled(true);
        txtTelefonoRegistro.setEnabled(true);
        txtMailRegistro.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRutRegistro = new javax.swing.JTextField();
        txtNombreRegistro = new javax.swing.JTextField();
        txtNombreContactoRegistro = new javax.swing.JTextField();
        txtTelefonoRegistro = new javax.swing.JTextField();
        txtWebRegistro = new javax.swing.JTextField();
        txtMailRegistro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIDadmin = new javax.swing.JTextField();
        txtIDProve = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbEstadoProv = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarProve = new javax.swing.JButton();
        btnModificarProve = new javax.swing.JButton();
        btnEliminarProve = new javax.swing.JButton();
        btnlimpiaRegistroProv = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarRegistro = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso Proveedores"));
        jPanel2.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel2.setText("RUT");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel3.setText("Contacto");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel4.setText("Nombre Proveedor");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel6.setText("Web");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel7.setText("Mail/Contacto");

        txtRutRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutRegistroFocusLost(evt);
            }
        });
        txtRutRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutRegistroActionPerformed(evt);
            }
        });
        txtRutRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutRegistroKeyTyped(evt);
            }
        });

        txtNombreContactoRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreContactoRegistroKeyTyped(evt);
            }
        });

        txtTelefonoRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoRegistroKeyTyped(evt);
            }
        });

        txtMailRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailRegistroFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setText("ID_Adm");

        txtIDadmin.setEditable(false);
        txtIDadmin.setText("1");

        txtIDProve.setEditable(false);
        txtIDProve.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel12.setText("ID_Prov");

        cbEstadoProv.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        cbEstadoProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "NO ACTIVO" }));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel13.setText("Estado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRutRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWebRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreContactoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtNombreRegistro)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailRegistro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIDProve, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEstadoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(cbEstadoProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreContactoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefonoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWebRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtIDProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 680, 210));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        btnAgregarProve.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnAgregarProve.setText("Agregar");
        btnAgregarProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveActionPerformed(evt);
            }
        });

        btnModificarProve.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnModificarProve.setText("Modificar");
        btnModificarProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProveActionPerformed(evt);
            }
        });

        btnEliminarProve.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnEliminarProve.setText("Eliminar");
        btnEliminarProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveActionPerformed(evt);
            }
        });

        btnlimpiaRegistroProv.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnlimpiaRegistroProv.setText("Limpiar");
        btnlimpiaRegistroProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiaRegistroProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarProve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarProve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarProve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiaRegistroProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProve)
                .addGap(18, 18, 18)
                .addComponent(btnModificarProve)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProve)
                .addGap(18, 18, 18)
                .addComponent(btnlimpiaRegistroProv)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 110, 210));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logochico.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 200, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jLabel9.setText("Registro De Proveedores");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 260, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 760, 100));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel10.setText("Listado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/orange-gradient-wallpaper-4422.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 480));
        getContentPane().add(txtBuscarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 80, -1));

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Volver Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cerrar Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutRegistroActionPerformed

    private void btnlimpiaRegistroProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiaRegistroProvActionPerformed
        txtBuscarRegistro.setText("");
        txtNombreRegistro.setText("");
        txtNombreContactoRegistro.setText("");
        txtMailRegistro.setText("");
        txtWebRegistro.setText("");
        txtTelefonoRegistro.setText("");
        txtRutRegistro.setText("");
        txtIDProve.setText("");
        if(txtIDProve.getText().isEmpty()){
            txtIDProve.setText(pdo.getMaxID()+"");
        }
        
    }//GEN-LAST:event_btnlimpiaRegistroProvActionPerformed

    private void btnAgregarProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveActionPerformed

        if(txtIDProve.getText().isEmpty()|| txtRutRegistro.getText().isEmpty() || txtNombreRegistro.getText().isEmpty()||
            txtNombreContactoRegistro.getText().isEmpty() || txtTelefonoRegistro.getText().isEmpty() ||
            txtWebRegistro.getText().isEmpty() || txtMailRegistro.getText().isEmpty() || txtIDadmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes llenar los Campos Solicitados");
        }else{
            Proveedor pro = new Proveedor();
            pro.setID_PROVEEDOR(Integer.parseInt(txtIDProve.getText()));
            pro.setRUT_PROVEEDOR(txtRutRegistro.getText());
            pro.setPROVEEDOR(txtNombreContactoRegistro.getText());
            pro.setNOMBRE_CONTACTO(txtNombreRegistro.getText());
            pro.setTELEFONOS(txtTelefonoRegistro.getText());
            pro.setSITIO_WEB(txtWebRegistro.getText());
            pro.setMAIL_PROVEEDOR(txtMailRegistro.getText());
            pro.setID_ADMIN(txtIDadmin.getText()); 
            pro.setESTADO_PROVEDOR(cbEstadoProv.getSelectedItem().toString());
            //String value = cbEstadoProv.getSelectedItem().toString();
            JOptionPane.showMessageDialog(null, "Grabado Existoso"); 
            String mensaje = pdo.agregarProveedor(pro);
            try {
                listarProve();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnAgregarProveActionPerformed

    private void btnModificarProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProveActionPerformed
        if(txtRutRegistro.getText().isEmpty() || txtNombreRegistro.getText().isEmpty()||
            txtNombreContactoRegistro.getText().isEmpty() || txtTelefonoRegistro.getText().isEmpty() ||
            txtWebRegistro.getText().isEmpty() || txtMailRegistro.getText().isEmpty() || txtIDadmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes llenar los Campos Solicitados");
        }else{
            Proveedor pro = new Proveedor();
            pro.setID_PROVEEDOR(Integer.parseInt(txtIDProve.getText()));
            pro.setRUT_PROVEEDOR(txtRutRegistro.getText());
            pro.setPROVEEDOR(txtNombreContactoRegistro.getText());
            pro.setNOMBRE_CONTACTO(txtNombreRegistro.getText());
            pro.setTELEFONOS(txtTelefonoRegistro.getText());
            pro.setSITIO_WEB(txtWebRegistro.getText());
            pro.setMAIL_PROVEEDOR(txtMailRegistro.getText());
            pro.setID_ADMIN(txtIDadmin.getText());
            pro.setESTADO_PROVEDOR(cbEstadoProv.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Modificado Existoso");
            String mensaje = pdo.modificarProveedor(pro);
            
            try {
                listarProve();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarProveedores.class.getName()).log(Level.SEVERE, null, ex);  
            }
        }
    }//GEN-LAST:event_btnModificarProveActionPerformed

    private void btnEliminarProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveActionPerformed
        if(txtRutRegistro.getText().isEmpty() || 
            txtNombreRegistro.getText().isEmpty()||
            txtNombreContactoRegistro.getText().isEmpty() 
            || txtTelefonoRegistro.getText().isEmpty() ||
            txtWebRegistro.getText().isEmpty() || 
            txtMailRegistro.getText().isEmpty() || 
            txtIDadmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes llenar los Campos Solicitados");
        }else{
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Desesa Borrar el Registro?, "
                + "Estos cambios no son Reversibles", 
                  " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
              getToolkit().beep();
              String mensaje = pdo.eliminarProveedor(Integer.parseInt(txtIDProve.getText()));
              System.out.println("Borrado Existos");
            }
            try {
                listarProve();
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_btnEliminarProveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int seleccion = jTable1.rowAtPoint(evt.getPoint());
        txtIDProve.setText(jTable1.getValueAt(seleccion, 0)+"");
        txtRutRegistro.setText(jTable1.getValueAt(seleccion, 1)+"");
        txtNombreContactoRegistro.setText(jTable1.getValueAt(seleccion, 2)+"");
        txtNombreRegistro.setText(jTable1.getValueAt(seleccion, 3)+"");
        txtMailRegistro.setText(jTable1.getValueAt(seleccion, 4)+"");
        txtWebRegistro.setText(jTable1.getValueAt(seleccion, 5)+"");
        txtTelefonoRegistro.setText(jTable1.getValueAt(seleccion, 6)+"");
        //txtIDadmin.setText(jTable1.getValueAt(seleccion, 7)+"");  
    }//GEN-LAST:event_jTable1MouseClicked

    //Validacion de Mail
    private void txtMailRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailRegistroFocusLost
        if(IsEmail.isEmail(txtMailRegistro.getText())){
            
        }else{
            JOptionPane.showMessageDialog(null, "Mail incorrecto","Debes ingresar un Formato de Email Correcto",
                JOptionPane.INFORMATION_MESSAGE);
            //txtMailRegistro.requestFocus();
        }
    }//GEN-LAST:event_txtMailRegistroFocusLost

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Volver Al menu Principal?, "
                + "Recuerda Guardar tus Cambios", 
                 " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
            try {
                InicioMenuPrincipalAdmin inicio = new InicioMenuPrincipalAdmin();
                inicio.setVisible(true);
                dispose();
                //System.exit(0);
            } catch (SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(RegistrarProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas Salir del Sistema?, "
                + "Recuerda Guardar tus Cambios", 
                  " Salir ",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if (pregunta == 0){
              getToolkit().beep();
              System.exit(0);
              System.out.println("Sistema Cerrado Correctamente");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtRutRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutRegistroFocusLost
        if(this.validaRut.validaRut(txtRutRegistro.getText())){
            
        }else if(this.txtRutRegistro.getText().isEmpty()){
            this.txtRutRegistro.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Rut  incorrecto","Debes ingresar un Formato Correcto",
            JOptionPane.INFORMATION_MESSAGE);
            txtRutRegistro.setText("");
            txtRutRegistro.requestFocus();  
        }
    }//GEN-LAST:event_txtRutRegistroFocusLost

    //Validadciones de Caracteres y Numeros
    private void txtNombreContactoRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreContactoRegistroKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            txtNombreContactoRegistro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo Letras");
        }
    }//GEN-LAST:event_txtNombreContactoRegistroKeyTyped

    private void txtTelefonoRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoRegistroKeyTyped
        char validar= evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            txtTelefonoRegistro.setText("");
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtTelefonoRegistroKeyTyped

    private void txtRutRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutRegistroKeyTyped
        
    }//GEN-LAST:event_txtRutRegistroKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProve;
    private javax.swing.JButton btnEliminarProve;
    private javax.swing.JButton btnModificarProve;
    private javax.swing.JButton btnlimpiaRegistroProv;
    private javax.swing.JComboBox<String> cbEstadoProv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarRegistro;
    private javax.swing.JTextField txtIDProve;
    private javax.swing.JTextField txtIDadmin;
    private javax.swing.JTextField txtMailRegistro;
    private javax.swing.JTextField txtNombreContactoRegistro;
    private javax.swing.JTextField txtNombreRegistro;
    private javax.swing.JTextField txtRutRegistro;
    private javax.swing.JTextField txtTelefonoRegistro;
    private javax.swing.JTextField txtWebRegistro;
    // End of variables declaration//GEN-END:variables

    
}
